ALTER TABLE jobs ADD COLUMN IF NOT EXISTS job_type         VARCHAR(30)  NOT NULL DEFAULT 'FIELD_SERVICE';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS machine_serial_no VARCHAR(100);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS estimate_text     VARCHAR(500);
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS pending_at        TIMESTAMPTZ;
